name: Solar system App 

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node_version: [18,20]
            operating_system: [ubuntu-latest, macos-latest]  

        runs-on: ${{ matrix.operating_system}}        
        steps:
            - name: checkout repo  
              uses: actions/checkout@v4.2.2 # built-in actions for reading files in the folder as i run on different machine
           
            - name: Setuo Node.js environment
              uses: actions/setup-node@v4.4.0
              with: # i don't specify the versions so i can pass the variable to it 
                node-version: ${{matrix.node_version}} 
            
            - name: install npm
              run: npm install    
              
            - name: unit testing
              run: npm test   # output--> test-result.xml but on the vm need to be on my device (upload build-artifact)
            
            - uses: actions/upload-artifact@v4
              with:
                name: moch-test-result
                path: test-results.xml # the file i know it will create it 
                


# محتاج اقرأ الفايلات من جوا الفولدر هنا ف لازم اقوله يأكسسها عادي 

# if command run in the steps 
# if action from built-in ones --> uses

#need nodejs and npm to be on the macos & ubuntu 
# ممكن ادور اعمل command اييه 
# او اشوف اصلا لو فيه Action جاهز
